server:
  port: 8081 #\u907F\u514D\u4E0E\u76D1\u63A7\u4E2D\u5FC3\u76848080\u7AEF\u53E3\u51B2\u7A81

dubbo:
  application:
    name: user-service-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  monitor:
    protocol: registry

